'use strict';
const { Op } = require('sequelize');
const { sequelize, PenawaranMatakuliah, PenawaranMatakuliahDetil, PenawaranMatakuliahProdi, SemesterProdi, Semester, ProgramStudi, Matakuliah, Kelas, JadwalKelas, Ruang } = require('../../models');
const { paginate } = require('../../helpers/listQuery');
const AppError = require('../../helpers/AppError');
const { restoreRecord } = require('../../helpers/softDelete');

const detailInclude = [{ model: Matakuliah, as: 'matakuliah', include: [{ model: ProgramStudi, as: 'programStudi' }] }, { model: Kelas, as: 'kelas', include: [{ model: JadwalKelas, as: 'jadwalKelas', include: [{ model: Ruang, as: 'ruang' }] }] }];
const include = [{ model: SemesterProdi, as: 'semesterProdi', include: [{ model: Semester, as: 'semester' }, { model: ProgramStudi, as: 'programStudi' }] }, { model: PenawaranMatakuliahDetil, as: 'matakuliahDitawarkan', include: detailInclude }, { model: PenawaranMatakuliahProdi, as: 'prodiTujuan', include: [{ model: ProgramStudi, as: 'programStudi' }] }];
const options = { searchFields: ['$matakuliahDitawarkan.matakuliah.kode_matakuliah$', '$matakuliahDitawarkan.matakuliah.nama_resmi$'], sortableFields: ['status','tanggal_mulai','tanggal_selesai','createdAt'], filterableFields: ['semester_prodi_id','status'], defaultInclude: include, findOptions: { subQuery: false, distinct: true } };
const list = (query) => paginate(PenawaranMatakuliah, query, options);
const getById = async (id, transaction) => { const row = await PenawaranMatakuliah.findByPk(id, { include, transaction }); if (!row) throw new AppError('Periode penawaran tidak ditemukan', 404); return row; };
const validateCourses = async (semesterProdiId, courses, transaction) => { const sp = await SemesterProdi.findByPk(semesterProdiId, { transaction }); if (!sp) throw new AppError('Semester prodi tidak ditemukan', 404); const ids = courses.map((x) => x.matakuliah_id); const count = await Matakuliah.count({ where: { id: ids, program_studi_id: sp.program_studi_id }, transaction }); if (count !== ids.length) throw new AppError('Semua matakuliah harus dimiliki program studi penyelenggara', 422); };
const syncCourses = async (header, courses, transaction) => { await validateCourses(header.semester_prodi_id, courses, transaction); const current = await PenawaranMatakuliahDetil.findAll({ where: { penawaran_matakuliah_id: header.id }, transaction }); const wanted = new Set(courses.map((x) => x.matakuliah_id)); const removed = current.filter((x) => !wanted.has(x.matakuliah_id)); if (removed.length && await Kelas.count({ where: { penawaran_matakuliah_id: removed.map((x) => x.id) }, transaction })) throw new AppError('Matakuliah dengan kelas tidak dapat dikeluarkan dari penawaran', 409); if (removed.length) await PenawaranMatakuliahDetil.destroy({ where: { id: removed.map((x) => x.id) }, transaction }); for (const course of courses) { const [row] = await PenawaranMatakuliahDetil.findOrCreate({ where: { penawaran_matakuliah_id: header.id, matakuliah_id: course.matakuliah_id }, defaults: course, transaction }); await row.update(course, { transaction }); } };
const save = (id, payload) => sequelize.transaction(async (transaction) => { const { prodi_tujuan = [], matakuliah, ...data } = payload; let header; if (id) { header = await PenawaranMatakuliah.findByPk(id, { transaction, lock: transaction.LOCK.UPDATE }); if (!header) throw new AppError('Periode penawaran tidak ditemukan', 404); if (header.status !== 'draft') throw new AppError('Hanya periode draft yang dapat diubah', 409); await header.update(data, { transaction }); } else { const existing = await PenawaranMatakuliah.findOne({ where: { semester_prodi_id: data.semester_prodi_id }, transaction }); if (existing) throw new AppError('Penawaran semester-prodi sudah dibuat', 409); header = await PenawaranMatakuliah.create(data, { transaction }); }
  if (matakuliah) await syncCourses(header, matakuliah, transaction); await PenawaranMatakuliahProdi.destroy({ where: { penawaran_matakuliah_id: header.id }, transaction }); if (prodi_tujuan.length) await PenawaranMatakuliahProdi.bulkCreate(prodi_tujuan.map((x) => ({ ...x, penawaran_matakuliah_id: header.id })), { transaction }); return getById(header.id, transaction); });
const bulkSync = (id, courses) => sequelize.transaction(async (transaction) => { const header = await PenawaranMatakuliah.findByPk(id, { transaction, lock: transaction.LOCK.UPDATE }); if (!header) throw new AppError('Periode penawaran tidak ditemukan', 404); if (header.status !== 'draft') throw new AppError('Hanya periode draft yang dapat disinkronkan', 409); await syncCourses(header, courses, transaction); return getById(id, transaction); });
const transition = (id, status) => sequelize.transaction(async (transaction) => { const row = await PenawaranMatakuliah.findByPk(id, { include: [{ model: PenawaranMatakuliahDetil, as: 'matakuliahDitawarkan' }], transaction, lock: transaction.LOCK.UPDATE }); if (!row) throw new AppError('Periode penawaran tidak ditemukan', 404); if (status === 'published' && (row.status !== 'draft' || !row.matakuliahDitawarkan.length)) throw new AppError('Draft harus memiliki matakuliah sebelum dipublikasikan', 409); if (status === 'closed' && row.status !== 'published') throw new AppError('Penawaran belum dipublikasikan', 409); await row.update({ status, published_at: status === 'published' ? new Date() : row.published_at, closed_at: status === 'closed' ? new Date() : null }, { transaction }); return getById(id, transaction); });
const catalog = async (query) => { const now = new Date(); const programStudiId = query.filter?.program_studi_id; const matakuliahId = query.filter?.matakuliah_id; const detailWhere = matakuliahId ? { matakuliah_id: matakuliahId } : undefined; const where = { status: 'published', [Op.and]: [{ [Op.or]: [{ tanggal_mulai: null }, { tanggal_mulai: { [Op.lte]: now } }] }, { [Op.or]: [{ tanggal_selesai: null }, { tanggal_selesai: { [Op.gte]: now } }] }] }; if (programStudiId) where[Op.and].push({ [Op.or]: [{ akses: 'semua' }, { '$prodiTujuan.program_studi_id$': programStudiId }] }); return paginate(PenawaranMatakuliah, query, { ...options, filterableFields: [], where, defaultInclude: include.map((item) => item.as === 'matakuliahDitawarkan' ? { ...item, where: detailWhere, required: Boolean(detailWhere) } : item) }); };
const remove = async (id) => { const row = await getById(id); if (row.status !== 'draft') throw new AppError('Hanya draft yang dapat dihapus', 409); await row.destroy(); return { id }; };
const assertSchedule = async (payload, excludeId, transaction) => { if (payload.jam_mulai >= payload.jam_selesai) throw new AppError('Jam selesai harus setelah jam mulai', 422); const conflict = await JadwalKelas.findOne({ where: { ruang_id: payload.ruang_id, hari: payload.hari, ...(excludeId ? { id: { [Op.ne]: excludeId } } : {}), jam_mulai: { [Op.lt]: payload.jam_selesai }, jam_selesai: { [Op.gt]: payload.jam_mulai } }, transaction }); if (conflict) throw new AppError('Jadwal bentrok pada ruang dan waktu tersebut', 409); };
const createSchedule = (detailId, classId, payload) => sequelize.transaction(async (transaction) => { const kelas = await Kelas.findOne({ where: { id: classId, penawaran_matakuliah_id: detailId }, transaction }); if (!kelas) throw new AppError('Kelas penawaran tidak ditemukan', 404); await assertSchedule(payload, null, transaction); return JadwalKelas.create({ ...payload, kelas_id: classId }, { transaction }); });
const updateSchedule = (detailId, classId, id, payload) => sequelize.transaction(async (transaction) => { const row = await JadwalKelas.findOne({ where: { id, kelas_id: classId }, include: [{ model: Kelas, as: 'kelas', where: { penawaran_matakuliah_id: detailId } }], transaction, lock: transaction.LOCK.UPDATE }); if (!row) throw new AppError('Jadwal tidak ditemukan', 404); await assertSchedule({ ...row.toJSON(), ...payload }, id, transaction); return row.update(payload, { transaction }); });
const deleteSchedule = async (detailId, classId, id) => { const row = await JadwalKelas.findOne({ where: { id, kelas_id: classId }, include: [{ model: Kelas, as: 'kelas', where: { penawaran_matakuliah_id: detailId } }] }); if (!row) throw new AppError('Jadwal tidak ditemukan', 404); await row.destroy(); return { id }; };
module.exports = { list, getById, create: (p) => save(null,p), update: save, bulkSync, remove, restore: (id) => restoreRecord(PenawaranMatakuliah,id,'Penawaran Matakuliah'), publish: (id) => transition(id,'published'), close: (id) => transition(id,'closed'), catalog, createSchedule, updateSchedule, deleteSchedule };
