'use strict';

const express = require('express');
const router = express.Router();

const authRoutes = require('./auth/auth.routes');
const usersRoutes = require('./iam/users.routes');
const rolesRoutes = require('./iam/roles.routes');
const permissionsRoutes = require('./iam/permissions.routes');
const activityLogsRoutes = require('./iam/activity-logs.routes');
const universitasRoutes = require('./institusi/universitas.routes');
const fakultasRoutes = require('./institusi/fakultas.routes');
const departemenRoutes = require('./institusi/departemen.routes');
const jenjangAkademikRoutes = require('./institusi/jenjang-akademik.routes');
const modelKurikulumRoutes = require('./institusi/model-kurikulum.routes');
const programStudiRoutes = require('./institusi/program-studi.routes');
const dosenRoutes = require('./institusi/dosen.routes');
const mahasiswaRoutes = require('./institusi/mahasiswa.routes');
const bimbinganAkademikRoutes = require('./institusi/bimbingan-akademik.routes');
const jenisSemesterRoutes = require('./semester/jenis-semester.routes');
const periodeRoutes = require('./semester/periode.routes');
const semesterRoutes = require('./semester/semester.routes');
const semesterProdiRoutes = require('./semester/semester-prodi.routes');
const kurikulumRoutes = require('./kurikulum/kurikulum.routes');
const sifatMatakuliahRoutes = require('./kurikulum/sifat-matakuliah.routes');
const tipeMatakuliahRoutes = require('./kurikulum/tipe-matakuliah.routes');
const matakuliahRoutes = require('./kurikulum/matakuliah.routes');
const matakuliahKurikulumRoutes = require('./kurikulum/matakuliah-kurikulum.routes');
const cpRoutes = require('./obe/cp.routes');
const scpRoutes = require('./obe/scp.routes');
const cpmkRoutes = require('./obe/cpmk.routes');
const sumberPenilaianRoutes = require('./obe/sumber-penilaian.routes');
const cpmkScpRoutes = require('./obe/cpmk-scp.routes');
const ruangRoutes = require('./perkuliahan/ruang.routes');
const kelasRoutes = require('./perkuliahan/kelas.routes');
const dosenKelasRoutes = require('./perkuliahan/dosen-kelas.routes');
const jadwalKelasRoutes = require('./perkuliahan/jadwal-kelas.routes');
const dosenJadwalRoutes = require('./perkuliahan/dosen-jadwal.routes');
const krsRoutes = require('./krs/krs.routes');
const krsDetilRoutes = require('./krs/krs-detil.routes');
const nilaiRoutes = require('./nilai/nilai.routes');
const historyUploadNilaiRoutes = require('./evaluasi/history-upload-nilai.routes');
const evaluasiCpmkRoutes = require('./evaluasi/evaluasi-cpmk.routes');
const rekapCpRoutes = require('./evaluasi/rekap-cp.routes');
const laporanCpRoutes = require('./evaluasi/laporan-cp.routes');
const dashboardRoutes = require('./dashboard/dashboard.routes');
const jenisDokumenEvaluasiRoutes = require('./evaluasi/jenis-dokumen-evaluasi.routes');
const dokumenEvaluasiRoutes = require('./evaluasi/dokumen-evaluasi.routes');

router.use('/auth', authRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/users', usersRoutes);
router.use('/roles', rolesRoutes);
router.use('/permissions', permissionsRoutes);
router.use('/activity-logs', activityLogsRoutes);
router.use('/universitas', universitasRoutes);
router.use('/fakultas', fakultasRoutes);
router.use('/departemen', departemenRoutes);
router.use('/jenjang-akademik', jenjangAkademikRoutes);
router.use('/model-kurikulum', modelKurikulumRoutes);
router.use('/program-studi', programStudiRoutes);
router.use('/dosen', dosenRoutes);
router.use('/mahasiswa', mahasiswaRoutes);
router.use('/bimbingan-akademik', bimbinganAkademikRoutes);
router.use('/jenis-semester', jenisSemesterRoutes);
router.use('/periode', periodeRoutes);
router.use('/semester', semesterRoutes);
router.use('/semester-prodi', semesterProdiRoutes);
router.use('/kurikulum', kurikulumRoutes);
router.use('/sifat-matakuliah', sifatMatakuliahRoutes);
router.use('/tipe-matakuliah', tipeMatakuliahRoutes);
router.use('/matakuliah', matakuliahRoutes);
router.use('/matakuliah-kurikulum', matakuliahKurikulumRoutes);
router.use('/cp', cpRoutes);
router.use('/scp', scpRoutes);
router.use('/cpmk', cpmkRoutes);
router.use('/sumber-penilaian', sumberPenilaianRoutes);
router.use('/cpmk-scp', cpmkScpRoutes);
router.use('/ruang', ruangRoutes);
router.use('/kelas', kelasRoutes);
router.use('/dosen-kelas', dosenKelasRoutes);
router.use('/jadwal-kelas', jadwalKelasRoutes);
router.use('/dosen-jadwal', dosenJadwalRoutes);
router.use('/krs', krsRoutes);
router.use('/krs-detil', krsDetilRoutes);
router.use('/nilai', nilaiRoutes);
router.use('/history-upload-nilai', historyUploadNilaiRoutes);
router.use('/evaluasi-cpmk', evaluasiCpmkRoutes);
router.use('/rekap-cp', rekapCpRoutes);
router.use('/laporan-cp', laporanCpRoutes);
router.use('/jenis-dokumen-evaluasi', jenisDokumenEvaluasiRoutes);
router.use('/dokumen-evaluasi', dokumenEvaluasiRoutes);

module.exports = router;
